### PR TITLE
Added Dump Handler and Mask template to code-gen

### PR DESCRIPTION
**Pull request by BalloonWen**
When use code-gen to generate code, will add DumpHandler to handler.yml and add mask.yml to the resources folder
related to issue: 
https://github.com/networknt/light-4j/issues/23
https://github.com/networknt/light-4j/issues/280

### CODE REVIEW

**Comment by stevehu** [comment]
I think we should comment out the dump handler in the generated handler.yml as it is not supposed to be used on production. If it is needed, the developer can enable it by uncommenting the handler. I am afraid it will be injected into production configuration if the users don't understand the impact. What do you think? Thanks.

**Comment by BalloonWen** [comment]
I think so too, so I commented out when define default handler chain, maybe
I should also comment it out in definition?

**Comment by stevehu** [comment]
I think that might be a good idea. Also adding a comment before the line to indicate when this handler should be used and why might be a good idea.

**Comment by BalloonWen** [comment]
I’ll do that.

**Comment by ddobrin** [comment]
@BalloonWen: there is a new parameter added, however could you please document how it would be used.

There is another issue created: #180, which is being worked on now and which aims to streamline the config.json and its parameters.  
How would this fit in and how do we avoind overlap and/or duplication

**Comment by stevehu** [comment]
@BalloonWen I had a chat with other developers who have some pending PRs on this repo. It looks like it is a good idea to merge all related PRs into a WIP branch is a good idea for an integration test. Would you be able to update the document for this PR so that others can easily evaluate the impact on their changes? Thanks.

**Comment by ddobrin** [comment]
@BalloonWen : 
I think that we need to comment out the dump handler in the chain in the Swagger portion of the . generator:
light-rest-4j/src/main/resources/templates/rest/swagger/handlerYml.rocker.raw.

I'll merge the PR into the WIP branch and comment it out there.

**Pull request merged**
