### PR TITLE
fixes #230 change verifyHostname to false in the generated client.yml

### LINKED ISSUE #230: change verifyHostname to false in the generated client.yml
A new feature has been added in release 1.5.29 to verify the hostname of the certificate if static IP is used and verify serviceId if dynamic IP is used. This is the feature mostly used on official testing and production environment and should be disabled for the dev environment as we normally only have a self-signed certificate for testing. In a long term, we will try to generate a certificate from light-codegen based on serviceid or dns, but until then, the default client.yml generated from light-codegen will have verifyHostname set to false in order to make default certificate work.

### PR DESCRIPTION
**Pull request by stevehu**

### CODE REVIEW

**Comment by NicholasAzar** [comment]
@stevehu I think I approved this a bit early without thinking through it too much. After a discussion I don't think it's right to have verifyHostname disabled by default. This would cause a mandatory step when moving to an upper environment to enable it, instead of having the developer explicitly disable it in their services..

**Comment by ddobrin** [comment]
@stevehu @NicholasAzar : do you guys agree that a start-up guide would be a good idea, where such issues are listed and made mandatory reading for consumers, maybe listed in **Bold** in the **light-codegen** documentation, **PLEASE read before starting development**

**Comment by NicholasAzar** [comment]
@ddobrin Yeah I think that's a good idea. And maybe even having the codegen cli output a link to that documentation site after it finishes generation (configurable so that different teams could have different landing pages?).
Are we ok with reverting this and going back to enable verify hostname by default? To help reduce impact on developers we could include "localhost" in the subject alternative names of the test certs right?

**Comment by stevehu** [comment]
Disabling it is only a temp solution. As I have commented, we should have the right self-signed certificate generated from the light-codegen in the next release. The problem I see is that it is very hard for the most developer to prepare keystores and we have to make it work out of the box for now until we have the final solution. I am open to any other workarounds.

**Comment by ddobrin** [comment]
I would not touch the change for this release. 

At least, not until a process is in place documenting everything and making it clearly for developers in terms of what needs to be done.

Existing users do not regenerate existing APIs and will be hit with the same issue right away. They just migrate

**Comment by NicholasAzar** [comment]
@ddobrin Developer on-boarding should not be a higher priority than security. By disabling hostname verification by default we introduce a possibility for clients to trust services they shouldn't unless they take an action for which we have not documented.
I should not have approved this change.

**Pull request merged**
