### PR TITLE
Fix/API-86: generate eclipse files based on the config flag

### PR DESCRIPTION
**Pull request by santoshaherkar**

### CODE REVIEW

**Comment by santoshaherkar** [comment]
@stevehu I had selected base branch as master but in actual PR it shows release.. is that because default branch is release?

I have added <repositories> tag in pom file to enable snapshots downloading and added sample config.json as well, just to get an idea about how that file should be.

**Comment by stevehu** [comment]
@santoshaherkar It is great to have this flag to control if the eclipse files are generated or not. There are some existing users expecting these files to be generated with their existing config.json file. I am wondering if we should make this flag default to true in the generator. I have include @ddobrin @chenyan71 as they have some developers using eclipse. What do you think?

**Comment by santoshaherkar** [comment]
@NicholasAzar do you agree with keeping this flag to true by default? Jira item mentions that eclipse file should not be created by default, so just wanted to confirm.

**Comment by NicholasAzar** [comment]
Currently i dont agree with that, as both eclipse and intellij can import projects just based on the pom.xml.. and the eclipse files actually just cause problems with intellij. Having them generated as default seems incorrect to me.
That being said if there's a push to keep this unchanged for whatever reason, then unfortunately we'll have to add another flag.

**Comment by stevehu** [comment]
@NicholasAzar These files were introduced in the early days of light-codegen. At that time, there were only several configuration options available and nobody ever thought to add a flag to enable/disable it. I am using IntelliJ IDEA and never encounter any problem with these two files. Did anybody report issues with these files? What was the issue? Thanks.

**Comment by stevehu** [comment]
@ddobrin I think you added these two files in the first place. Are you OK to not generate these files by default? Can eclipse generate these files by importing pom.xml?

**Comment by ddobrin** [comment]
@stevehu: we can just set the default to false and that's it.
"eclipseIDE": false,

Or, we can set the default value to false in the code and, if somebody sets the flag, it can be generated.

Eclipse, unfortunately has issues with importing pom files.

If you guys don't wish to have this at all, please update the issue here for confirmation  and I will address it separately for my client.

**Comment by stevehu** [comment]
@ddobrin Thanks Dan for the confirmation. The implementation is exactly what you have described.

**Comment by stevehu** [comment]
[generate eclipse files based on the config flag](https://trello.com/c/BzQqrik8/205-generate-eclipse-files-based-on-the-config-flag)

**Pull request merged**
