### PR TITLE
Feat/388 generation of one of artifacts

### PR DESCRIPTION
**Pull request by jiachen1120**
Related doc: https://github.com/networknt/light-rfcs/pull/39
Related issue: https://github.com/networknt/light-codegen/issues/388

### CODE REVIEW

**Comment by miklish** [comment]
Looks good!

As we discussed offline, it would be good to add some additional comments.

Also--in `OpenApiGenerator.loadModel()`--I think the code could be made clearer by changing the variable name of `schemaQueue`, `currentSchema`, `currentSchemaKey`, to something that describes the fact that these are schema elements and do not usually refer the root of a full schema. E.g.: Perhaps  `schemaElementQueue`, `currentElement`, `currentElementKey`.

Other than that, I'm ready to approve.

**Comment by jiachen1120** [comment]
@miklish Thanks for the helpful suggestion! I already added the comments and changed the variable name to be more specific :)

**Comment by miklish** [comment]
Thanks @jiachen1120!

@ddobrin @stevehu Please review and approve the PR when you can.

**Comment by ddobrin** [comment]
Guys,
I can't test this feature out at this time, as we have API deliveries this week and I am busy with it. 

I don't want to hold the codegen release up and I can test it next week. If I encounter issues, we can work on a new release. 

I am leaving it up to @stevehu

**Pull request merged**
