### PR TITLE
Feat/#239 when generate test cases for handler, now will use example of request body to test.

### PR DESCRIPTION
**Pull request by BalloonWen**
related issue: https://github.com/networknt/light-codegen/issues/239
when generate test cases for handler, now will use example of request body to test.

### CODE REVIEW

**Comment by NicholasAzar** [comment]
@BalloonWen could you resolve the conflicts?

**Comment by jiachen1120** [comment]
@NicholasAzar @stevehu @BalloonWen  Hey! I have further improved this feature. Look forward to your review!

**Comment by stevehu** [comment]
@jiachen1120 Have you encountered any issue with the rocker 1.2.1? The new rocker version handles the whitespaces much better. I have reviewed the changelog and couldn't find any compatibility issue. I am wondering if we should give it a try since the generated code formatted much better than before.

**Comment by 243826** [comment]
@stevehu I am not sure whether it's newer version of rocker. I had to spend
some time  to achieve the formatting you observed in my PR.

**Comment by stevehu** [comment]
@243826 Thanks for the confirmation. I didn't realize that the format is purely done manually. Nice job!!! I am still thinking that we should try out the latest version until we encounter some issues. Then we can rollback to 1.0.0 instead of 0.22 as it is not supposed for production usage in common practice.

**Comment by jiachen1120** [comment]
@stevehu Good morning! Yesterday I used the new version and found that I couldn't compile, the problem I thought was about rocker, and then I just found out that it was actually a problem with my IDE. Has been resolved and updated the rocker version to 1.2.1

**Pull request merged**
