### PR TITLE
added feature to generate test cases based on specification

### PR DESCRIPTION
**Pull request by BalloonWen**
related issue: https://github.com/networknt/light-codegen/issues/133

### CODE REVIEW

**Comment by NicholasAzar** [comment]
Would it be possible to remove the dependency on "generex" and implement that type of random string functionality on your own?

**Comment by BalloonWen** [comment]
This library "generex" is specific for generating String that matches a given regular expression.
Even if I write by myself, it will be similar but may not be better as it's tested by many people.
Unless it has some serious bugs, then we need to consider writing by ourselves.

**Comment by stevehu** [comment]
The generex has a dependency automaton which is licensed under BSD 2-clause. It requires we put the copyright and license file somewhere when distributed. I am not sure how to do that yet.

**Comment by BalloonWen** [comment]
@stevehu @NicholasAzar 
what should I do then -.-
Should we just give up the pattern part? Not quite sure if it's a common requirement which needs to put a lot of effort on.

**Comment by stevehu** [comment]
I really appreciate the effort to make the test cases closer to the real scenarios; however, there is no way to make it perfect as it would be another full-blown project. If we can generate the values based on the correct type(integer/string) with some limitations(length, max, min etc.), it would be good enough. For the developers who are working on the test cases, they need to modify it anyway. What do you think?

**Comment by stevehu** [comment]
@NicholasAzar Do you know how to properly handle the license of automaton which BSD 2 Clause. It is not the direct dependency and it is not part of the light-4j delivery. However, the customers who are using light-4j might be on the hook. To handle this scenario, we have to hire a lawyer to figure out how to handle it properly. So far, we only have Apache 2.0 and MIT licenses in our dependencies. If we include any other licensed library, we are putting our customers in a position that they might be sued.

**Comment by ddobrin** [comment]
If we promote the dependency with this change, we need to advise our respective client(s) before they use this version.

I am not sure whether a software such as BlackDuck should flag whether this dependency creates an issue or not

**Comment by ddobrin** [comment]
@stevehu, @NicholasAzar 
I have reviewed this change offline with the latest update from @BalloonWen .

It fixes the generation problem and all APIs at my client are generating and building generated code without errors.

This PR has an associated PR in light-rest-4jL:
https://github.com/networknt/light-rest-4j/pull/69

They both can be merged at this time.

**Comment by BalloonWen** [comment]
The code was changed to add test ignore.
As discussed @ddobrin @stevehu  these generated tests should validate response based on the schema, but right after running codegen, there isn't any business to send response yet, which will cause tests failure. Thus, we should add ignore annotation to pass the build. Whenever a developer wants to use this feature, the developer can just remove the annotation.

**Pull request merged**
