### PR TITLE
View initial commit

### PR DESCRIPTION
**Pull request by NicholasAzar**
Hi Steve, don't have access to push directly, this is my initial templating for the view

### CODE REVIEW

**Comment by NicholasAzar** [comment]
view prelim screenshot: https://snag.gy/Eilzda.jpg

**Comment by stevehu** [comment]
Have you tried to push? You should have access. Let me know if you have issues.

**Comment by NicholasAzar** [comment]
@stevehu Yeah i tried last night and again just now, access denied, i think the issue is that the 'light-codegen' team is missing the light-codegen repository.

**Comment by stevehu** [comment]
My mistake. It is fixed now for the repo access. Thanks.

**Pull request merged**
