### PR TITLE
add openAPI spec generator - #197

### PR DESCRIPTION
**Pull request by dz-1**

### CODE REVIEW

**Comment by NicholasAzar** [comment]
@dz-1 is there an rfc for this or issue #?

**Comment by dz-1** [comment]
@NicholasAzar This is for jira issue 'API-83'  and issue #197.

**Comment by NicholasAzar** [comment]
@dz-1 thanks! Is there any documentation about how to use this?

**Comment by dz-1** [comment]
@NicholasAzar 
I have updated the doc [light-codegen](https://github.com/networknt/light-doc/blob/next/content/en/tool/light-codegen/openapi-generator.md).

**Pull request merged**
