### PR TITLE
Remove FrameworkRegistry in favor of standard ServiceLoader API

### PR DESCRIPTION
**Pull request by cchacin**

### CODE REVIEW

**Comment by stevehu** [comment]
@cchacin Any particular reason to make this change? When we deploy the light-codegen as a web service, it is very important to externalize the generators so that we can adjust the configuration outside the binary package and the service.yml is one of the config files. Take a look at this file that has more dependency injections than the generators. 

https://github.com/networknt/light-config-test/blob/master/light-codegen/2_0_x/config/service.yml

**Comment by cchacin** [comment]
@stevehu the change is just to use a standard mechanism for those injections, but I wasn't aware that [FrameworkRegistry](https://github.com/networknt/light-codegen/blob/master/codegen-fwk/src/main/java/com/networknt/codegen/FrameworkRegistry.java) was also used for other kinds of injection.

Can we consider keeping the [FrameworkRegistry](https://github.com/networknt/light-codegen/blob/master/codegen-fwk/src/main/java/com/networknt/codegen/FrameworkRegistry.java) for the other purposes and using `ServiceLoader` API for the generators?

In that way, the injection of `Generator`s can be done using the service loader and there is no need for a custom `.yml` file and you can continue using the `FrameworkRegistry` as usual for the other use cases.

What do you think?

**Comment by stevehu** [comment]
The Java standard ServiceLoader has very limited features and we have replaced it with [config module](https://doc.networknt.com/concern/config/) of light-4j to support externalized configuration with environment variable override and config server. Along with the config module, we have developed IoC module [service](https://doc.networknt.com/concern/service/) which is very small and fast.

**Comment by cchacin** [comment]
@stevehu thanks for the clarification, I'll close this PR since there is no reason to maintain 2 different ways of injection. 👍

**Comment by stevehu** [comment]
@cchacin We really appreciate your help. Let's open an issue to discuss the solution next time so that everybody will be on the same page before we dive into the implementation. Thanks.

**Comment by cchacin** [comment]
@stevehu in this particular case, I evaluated that the time for creating the issue was possibly bigger than the time to submit this small PR, but I agree with the approach for bigger or more complex changes

**Pull request closed without merging**
